name: livefit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5080142510123551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aaa9a9'
    - '#ffffff'
    - '#031632'
    - '#ab6272'
    - '#09da3a'
  brandStrength: 1
  lightness: 0.8279497816693038
  saturation: 1
  rhythmicContrast: 0.2291111098602414
purpose: []
